import { Question } from "@/types";

export type QuestionBank = Record<string, Question[]>;

export function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

export function getQuestions(gameSlug: string): Question[] {
  const bank = questionBanks[gameSlug];
  if (!bank) return [];
  return shuffle(bank);
}

export const questionBanks: QuestionBank = {
  "tebak-huruf": [
    { id: "th1", question: "Huruf apa yang merupakan huruf pertama dari kata 'APLE'?", options: ["A", "B", "C", "D"], answer: "A", difficulty: "Mudah", category: "Huruf" },
    { id: "th2", question: "Huruf apa yang hilang dari kata '_UTA'?", options: ["R", "S", "T", "P"], answer: "R", difficulty: "Mudah", category: "Huruf" },
    { id: "th3", question: "Huruf kapital yang berbeda dari yang lain adalah?", options: ["A", "b", "C", "D"], answer: "b", difficulty: "Mudah", category: "Huruf" },
    { id: "th4", question: "Huruf terakhir dari alphabet adalah?", options: ["X", "Y", "Z", "W"], answer: "Z", difficulty: "Mudah", category: "Huruf" },
    { id: "th5", question: "Huruf apa yang berbunyi seperti 'ef'?", options: ["E", "F", "S", "G"], answer: "F", difficulty: "Sedang", category: "Huruf" },
    { id: "th6", question: "Pasangan huruf besar dan kecil yang benar adalah?", options: ["G-g", "H-h", "I-i", "Semua benar"], answer: "Semua benar", difficulty: "Sedang", category: "Huruf" },
    { id: "th7", question: "Huruf vokal yang ada di tengah alphabet adalah?", options: ["A", "I", "U", "O"], answer: "I", difficulty: "Sedang", category: "Huruf" },
    { id: "th8", question: "Jika balik, huruf apa yang tetap sama?", options: ["M", "N", "A", "H"], answer: "A", difficulty: "Sulit", category: "Huruf" },
    { id: "th9", question: "Huruf yang sering digunakan dalam singkatan 'Rp' adalah?", options: ["R", "P", "B", "D"], answer: "R", difficulty: "Mudah", category: "Huruf" },
    { id: "th10", question: "Huruf ke-5 dari alphabet adalah?", options: ["D", "E", "F", "G"], answer: "E", difficulty: "Mudah", category: "Huruf" },
    { id: "th11", question: "Huruf yang ada di antara J dan L adalah?", options: ["I", "K", "M", "H"], answer: "K", difficulty: "Sedang", category: "Huruf" },
    { id: "th12", question: "Huruf apa yang merupakan singkatan dari 'Indonesia'?", options: ["I", "ID", "IN", "IND"], answer: "I", difficulty: "Mudah", category: "Huruf" },
  ],

  "tebak-kata": [
    { id: "tk1", question: "Apa kata yang terbentuk dari huruf 'A-N-J-I-N-G'?", options: ["Anjing", "Anjir", "Anjat", "Anjar"], answer: "Anjing", difficulty: "Mudah", category: "Kata" },
    { id: "tk2", question: "Kata 'B-U-U' berarti?", options: ["Buang", "Buah", "Buku", "Buru"], answer: "Buah", difficulty: "Mudah", category: "Kata" },
    { id: "tk3", question: "Apa arti kata 'C-A-H-A-Y-A'?", options: ["Cahaya", "Cakra", "Catur", "Catur"], answer: "Cahaya", difficulty: "Mudah", category: "Kata" },
    { id: "tk4", question: "Kata 'D-U-N-I-A' berarti?", options: ["Dunia", "Duri", "Duta", "Duka"], answer: "Dunia", difficulty: "Mudah", category: "Kata" },
    { id: "tk5", question: "Apa arti kata 'E-L-A-N-G'?", options: ["Elang", "Emas", "Enam", "Energi"], answer: "Elang", difficulty: "Sedang", category: "Kata" },
    { id: "tk6", question: "Kata 'F-A-L-A-S-A-H' berarti?", options: ["Fakta", "Falsa", "Fantasi", "Falsafah"], answer: "Falsafah", difficulty: "Sedang", category: "Kata" },
    { id: "tk7", question: "Apa arti kata 'G-U-R-U'?", options: ["Guru", "Gula", "Guru", "Guna"], answer: "Guru", difficulty: "Mudah", category: "Kata" },
    { id: "tk8", question: "Kata 'H-U-T-A-N' berarti?", options: ["Hutan", "Hujan", "Hutan", "Hujan"], answer: "Hutan", difficulty: "Mudah", category: "Kata" },
    { id: "tk9", question: "Apa arti kata 'I-B-U'?", options: ["Ibu", "Ikan", "Ilmu", "Iman"], answer: "Ibu", difficulty: "Mudah", category: "Kata" },
    { id: "tk10", question: "Kata 'J-A-R-I-N-G-A-N' berarti?", options: ["Jaringan", "Jarum", "Jangkrik", "Jarak"], answer: "Jaringan", difficulty: "Sedang", category: "Kata" },
    { id: "tk11", question: "Apa arti kata 'K-A-R-T-U'?", options: ["Kartu", "Kapur", "Karakter", "Karung"], answer: "Kartu", difficulty: "Mudah", category: "Kata" },
    { id: "tk12", question: "Kata 'L-A-M-P-U' berarti?", options: ["Lampu", "Lumpur", "Lancar", "Lari"], answer: "Lampu", difficulty: "Mudah", category: "Kata" },
  ],

  "puzzle-kata": [
    { id: "pk1", question: "Susun huruf ini menjadi kata yang benar: L-A-M-P-U", answer: "Lampu", difficulty: "Mudah", category: "Puzzle Kata" },
    { id: "pk2", question: "Susun huruf ini menjadi kata yang benar: M-A-J-A-L-A-H", answer: "Majalah", difficulty: "Mudah", category: "Puzzle Kata" },
    { id: "pk3", question: "Susun huruf ini menjadi kata yang benar: S-E-K-O-L-A-H", answer: "Sekolah", difficulty: "Mudah", category: "Puzzle Kata" },
    { id: "pk4", question: "Susun huruf ini menjadi kata yang benar: G-A-M-B-A-R", answer: "Gambar", difficulty: "Mudah", category: "Puzzle Kata" },
    { id: "pk5", question: "Susun huruf ini menjadi kata yang benar: P-E-N-C-A-R-I", answer: "Pencari", difficulty: "Sedang", category: "Puzzle Kata" },
    { id: "pk6", question: "Susun huruf ini menjadi kata yang benar: P-E-R-J-A-L-A-N-A-N", answer: "Perjalanan", difficulty: "Sedang", category: "Puzzle Kata" },
    { id: "pk7", question: "Susun huruf ini menjadi kata yang benar: K-E-P-A-L-A", answer: "Kepala", difficulty: "Mudah", category: "Puzzle Kata" },
    { id: "pk8", question: "Susun huruf ini menjadi kata yang benar: R-A-H-A-S-I-A", answer: "Rahasia", difficulty: "Sedang", category: "Puzzle Kata" },
    { id: "pk9", question: "Susun huruf ini menjadi kata yang benar: P-E-N-G-A-L-A-M-A-N", answer: "Pengalaman", difficulty: "Sulit", category: "Puzzle Kata" },
    { id: "pk10", question: "Susun huruf ini menjadi kata yang benar: K-E-B-U-D-A-Y-A-A-N", answer: "Kebudayaan", difficulty: "Sulit", category: "Puzzle Kata" },
    { id: "pk11", question: "Susun huruf ini menjadi kata yang benar: B-E-L-A-J-A-R", answer: "Belajar", difficulty: "Mudah", category: "Puzzle Kata" },
    { id: "pk12", question: "Susun huruf ini menjadi kata yang benar: M-A-T-A-P-E-L-A-J-A-R-A-N", answer: "Mata Pelajaran", difficulty: "Sulit", category: "Puzzle Kata" },
  ],

  "puzzle-kalimat": [
    { id: "pkl1", question: "Susun kata-kata ini menjadi kalimat yang benar: 'adalah / Indonesia / negara / kita'", answer: "Indonesia adalah negara kita", difficulty: "Mudah", category: "Puzzle Kalimat" },
    { id: "pkl2", question: "Susun kata-kata ini menjadi kalimat yang benar: 'belajar / kita / harus'", answer: "Kita harus belajar", difficulty: "Mudah", category: "Puzzle Kalimat" },
    { id: "pkl3", question: "Susun kata-kata ini menjadi kalimat yang benar: 'saya / sekolah / pergi / ke'", answer: "Saya pergi ke sekolah", difficulty: "Mudah", category: "Puzzle Kalimat" },
    { id: "pkl4", question: "Susun kata-kata ini menjadi kalimat yang benar: 'indah / sangat / alam / itu'", answer: "Alam itu sangat indah", difficulty: "Sedang", category: "Puzzle Kalimat" },
    { id: "pkl5", question: "Susun kata-kata ini menjadi kalimat yang benar: 'anak-anak / bermain / taman / di'", answer: "Anak-anak bermain di taman", difficulty: "Sedang", category: "Puzzle Kalimat" },
    { id: "pkl6", question: "Susun kata-kata ini menjadi kalimat yang benar: 'guru / mengajar / kelas / di'", answer: "Guru mengajar di kelas", difficulty: "Mudah", category: "Puzzle Kalimat" },
    { id: "pkl7", question: "Susun kata-kata ini menjadi kalimat yang benar: 'kami / ke / pergi / library'", answer: "Kami pergi ke perpustakaan", difficulty: "Sedang", category: "Puzzle Kalimat" },
    { id: "pkl8", question: "Susun kata-kata ini menjadi kalimat yang benar: 'adik / membaca / buku / sedang'", answer: "Adik sedang membaca buku", difficulty: "Sedang", category: "Puzzle Kalimat" },
    { id: "pkl9", question: "Susun kata-kata ini menjadi kalimat yang benar: 'hari / cerah / ini / sangat'", answer: "Hari ini sangat cerah", difficulty: "Mudah", category: "Puzzle Kalimat" },
    { id: "pkl10", question: "Susun kata-kata ini menjadi kalimat yang benar: 'menulis / dia / surat / sedang'", answer: "Dia sedang menulis surat", difficulty: "Sedang", category: "Puzzle Kalimat" },
    { id: "pkl11", question: "Susun kata-kata ini menjadi kalimat yang benar: 'ibukota / Jakarta / Indonesia / adalah'", answer: "Jakarta adalah ibukota Indonesia", difficulty: "Sedang", category: "Puzzle Kalimat" },
    { id: "pkl12", question: "Susun kata-kata ini menjadi kalimat yang benar: 'belajar / sambil / menyenangkan / bermain'", answer: "Belajar sambil bermain menyenangkan", difficulty: "Sulit", category: "Puzzle Kalimat" },
  ],

  "tebak-gambar": [
    { id: "tga1", question: "Apa nama hewan yang suka berenang di air ini? 🐠", options: ["Ikan", "Burung", "Kucing", "Anjing"], answer: "Ikan", difficulty: "Mudah", category: "Tebak Gambar" },
    { id: "tga2", question: "Benda apa yang digunakan untuk menulis ini? 🖊️", options: ["Pensil", "Pulpen", "Penggaris", "Pensil Warna"], answer: "Pulpen", difficulty: "Mudah", category: "Tebak Gambar" },
    { id: "tga3", question: "Buah apa yang berwarna merah ini? 🍎", options: ["Apel", "Pisang", "Anggur", "Jeruk"], answer: "Apel", difficulty: "Mudah", category: "Tebak Gambar" },
    { id: "tga4", question: "Alat transportasi apa yang terbang di langit? ✈️", options: ["Kereta", "Pesawat", "Sepeda", "Kapal"], answer: "Pesawat", difficulty: "Mudah", category: "Tebak Gambar" },
    { id: "tga5", question: "Hewan apa yang suka makan bambu? 🐼", options: ["Beruang", "Panda", "Singa", "Gajah"], answer: "Panda", difficulty: "Sedang", category: "Tebak Gambar" },
    { id: "tga6", question: "Benda apa yang digunakan untuk melihat bintang? 🔭", options: ["Kaca Pembesar", "Teropong", "Kamera", "Mikroskop"], answer: "Teropong", difficulty: "Sedang", category: "Tebak Gambar" },
    { id: "tga7", question: "Buah apa yang berwarna kuning dan panjang? 🍌", options: ["Mangga", "Pisang", "Jeruk", "Semangka"], answer: "Pisang", difficulty: "Mudah", category: "Tebak Gambar" },
    { id: "tga8", question: "Alat musik apa yang dipetik ini? 🎸", options: ["Piano", "Gitar", "Drum", "Seruling"], answer: "Gitar", difficulty: "Mudah", category: "Tebak Gambar" },
    { id: "tga9", question: "Hewan apa yang bisa terbang ini? 🦅", options: ["Burung", "Kucing", "Ikan", "Kuda"], answer: "Burung", difficulty: "Mudah", category: "Tebak Gambar" },
    { id: "tga10", question: "Alat apa yang digunakan untuk memotong kertas? ✂️", options: ["Gunting", "Pisau", "Silet", "Cutter"], answer: "Gunting", difficulty: "Mudah", category: "Tebak Gambar" },
    { id: "tga11", question: "Benda apa yang digunakan untuk menunjuk arah? 🧭", options: ["Jam", "Kompas", "Termometer", "Timbangan"], answer: "Kompas", difficulty: "Sedang", category: "Tebak Gambar" },
    { id: "tga12", question: "Hewan apa yang memiliki belalai panjang? 🐘", options: ["Badak", "Gajah", "Kuda Nil", "Jerapah"], answer: "Gajah", difficulty: "Mudah", category: "Tebak Gambar" },
  ],

  "mencocokkan-gambar": [
    { id: "mg1", question: "Cocokkan pasangan yang benar: Matahari -", options: ["Bulan", "Cahaya", "Bintang", "Awan"], answer: "Cahaya", difficulty: "Mudah", category: "Mencocokkan Gambar" },
    { id: "mg2", question: "Cocokkan pasangan yang benar: Air -", options: ["Api", "Tanah", "Es", "Udara"], answer: "Es", difficulty: "Mudah", category: "Mencocokkan Gambar" },
    { id: "mg3", question: "Cocokkan pasangan yang benar: Buah Apel -", options: ["Hijau", "Merah", "Biru", "Hitam"], answer: "Merah", difficulty: "Mudah", category: "Mencocokkan Gambar" },
    { id: "mg4", question: "Cocokkan pasangan yang benar: Hujan -", options: ["Awan", "Petir", "Pelangi", "Gunting"], answer: "Awan", difficulty: "Sedang", category: "Mencocokkan Gambar" },
    { id: "mg5", question: "Cocokkan pasangan yang benar: Pohon -", options: ["Batu", "Daun", "Api", "Air"], answer: "Daun", difficulty: "Mudah", category: "Mencocokkan Gambar" },
    { id: "mg6", question: "Cocokkan pasangan yang benar: Sekolah -", options: ["Rumah", "Guru", "Kantor", "Toko"], answer: "Guru", difficulty: "Sedang", category: "Mencocokkan Gambar" },
    { id: "mg7", question: "Cocokkan pasangan yang benar: Kucing -", options: ["Anjing", "Meong", "Mengeong", "Ikan"], answer: "Ikan", difficulty: "Sedang", category: "Mencocokkan Gambar" },
    { id: "mg8", question: "Cocokkan pasangan yang benar: Mata -", options: ["Telinga", "Melihat", "Hidung", "Mulut"], answer: "Melihat", difficulty: "Sedang", category: "Mencocokkan Gambar" },
    { id: "mg9", question: "Cocokkan pasangan yang benar: Pensil -", options: ["Pena", "Tulis", "Penghapus", "Kertas"], answer: "Tulis", difficulty: "Sedang", category: "Mencocokkan Gambar" },
    { id: "mg10", question: "Cocokkan pasangan yang benar: Api -", options: ["Air", "Panas", "Es", "Dingin"], answer: "Panas", difficulty: "Mudah", category: "Mencocokkan Gambar" },
    { id: "mg11", question: "Cocokkan pasangan yang benar: Pagi -", options: ["Malam", "Siang", "Sore", "Tidur"], answer: "Siang", difficulty: "Sedang", category: "Mencocokkan Gambar" },
    { id: "mg12", question: "Cocokkan pasangan yang benar: Gajah -", options: ["Kecil", "Belalai", "Sayap", "Ekor"], answer: "Belalai", difficulty: "Sedang", category: "Mencocokkan Gambar" },
  ],

  "matematika-cepat": [
    { id: "mc1", question: "12 + 8 = ?", options: ["18", "20", "22", "19"], answer: "20", difficulty: "Mudah", category: "Matematika Cepat" },
    { id: "mc2", question: "15 - 7 = ?", options: ["9", "8", "7", "10"], answer: "8", difficulty: "Mudah", category: "Matematika Cepat" },
    { id: "mc3", question: "6 × 7 = ?", options: ["42", "48", "36", "44"], answer: "42", difficulty: "Mudah", category: "Matematika Cepat" },
    { id: "mc4", question: "48 ÷ 6 = ?", options: ["8", "7", "9", "6"], answer: "8", difficulty: "Mudah", category: "Matematika Cepat" },
    { id: "mc5", question: "25 + 37 = ?", options: ["62", "61", "63", "64"], answer: "62", difficulty: "Sedang", category: "Matematika Cepat" },
    { id: "mc6", question: "100 - 43 = ?", options: ["57", "58", "56", "55"], answer: "57", difficulty: "Sedang", category: "Matematika Cepat" },
    { id: "mc7", question: "12 × 5 = ?", options: ["60", "55", "65", "50"], answer: "60", difficulty: "Sedang", category: "Matematika Cepat" },
    { id: "mc8", question: "72 ÷ 8 = ?", options: ["9", "8", "7", "10"], answer: "9", difficulty: "Sedang", category: "Matematika Cepat" },
    { id: "mc9", question: "99 + 11 = ?", options: ["110", "100", "109", "111"], answer: "110", difficulty: "Sedang", category: "Matematika Cepat" },
    { id: "mc10", question: "144 ÷ 12 = ?", options: ["12", "11", "13", "14"], answer: "12", difficulty: "Sedang", category: "Matematika Cepat" },
    { id: "mc11", question: "15 × 15 = ?", options: ["225", "215", "235", "245"], answer: "225", difficulty: "Sulit", category: "Matematika Cepat" },
    { id: "mc12", question: "250 - 175 = ?", options: ["75", "85", "65", "95"], answer: "75", difficulty: "Sedang", category: "Matematika Cepat" },
  ],

  "balapan-hitung": [
    { id: "bh1", question: "Angka ke-3 dalam deretan bilangan ganjil adalah?", options: ["5", "3", "7", "9"], answer: "5", difficulty: "Mudah", category: "Balapan Hitung" },
    { id: "bh2", question: "Berapa jumlah sisi pada segitiga?", options: ["2", "3", "4", "5"], answer: "3", difficulty: "Mudah", category: "Balapan Hitung" },
    { id: "bh3", question: "5 + 5 + 5 = ?", options: ["15", "20", "10", "25"], answer: "15", difficulty: "Mudah", category: "Balapan Hitung" },
    { id: "bh4", question: "2 × 3 × 4 = ?", options: ["24", "20", "18", "22"], answer: "24", difficulty: "Sedang", category: "Balapan Hitung" },
    { id: "bh5", question: "Berapa jumlah jari tangan manusia?", options: ["10", "8", "12", "6"], answer: "10", difficulty: "Mudah", category: "Balapan Hitung" },
    { id: "bh6", question: "100 ÷ 4 = ?", options: ["25", "20", "30", "15"], answer: "25", difficulty: "Mudah", category: "Balapan Hitung" },
    { id: "bh7", question: "Angka ke-5 dalam hitungan mundur dari 10 adalah?", options: ["5", "6", "4", "7"], answer: "5", difficulty: "Sedang", category: "Balapan Hitung" },
    { id: "bh8", question: "Berapa jumlah jam dalam satu hari?", options: ["24", "12", "48", "36"], answer: "24", difficulty: "Sedang", category: "Balapan Hitung" },
    { id: "bh9", question: "20 × 3 = ?", options: ["60", "50", "70", "40"], answer: "60", difficulty: "Sedang", category: "Balapan Hitung" },
    { id: "bh10", question: "Berapa jumlah bulan dalam setahun?", options: ["12", "10", "11", "13"], answer: "12", difficulty: "Mudah", category: "Balapan Hitung" },
    { id: "bh11", question: "13 + 14 + 15 = ?", options: ["42", "41", "43", "40"], answer: "42", difficulty: "Sedang", category: "Balapan Hitung" },
    { id: "bh12", question: "Berapa jumlah hari dalam seminggu?", options: ["7", "5", "6", "8"], answer: "7", difficulty: "Mudah", category: "Balapan Hitung" },
  ],

  "tangkap-angka": [
    { id: "ta1", question: "Tangkap angka yang merupakan hasil dari 3 + 4", answer: "7", difficulty: "Mudah", category: "Tangkap Angka" },
    { id: "ta2", question: "Tangkap angka yang merupakan hasil dari 10 - 3", answer: "7", difficulty: "Mudah", category: "Tangkap Angka" },
    { id: "ta3", question: "Tangkap angka yang merupakan hasil dari 6 × 2", answer: "12", difficulty: "Mudah", category: "Tangkap Angka" },
    { id: "ta4", question: "Tangkap angka yang merupakan hasil dari 15 ÷ 3", answer: "5", difficulty: "Mudah", category: "Tangkap Angka" },
    { id: "ta5", question: "Tangkap angka yang merupakan hasil dari 8 + 9", answer: "17", difficulty: "Sedang", category: "Tangkap Angka" },
    { id: "ta6", question: "Tangkap angka yang merupakan hasil dari 20 - 7", answer: "13", difficulty: "Sedang", category: "Tangkap Angka" },
    { id: "ta7", question: "Tangkap angka yang merupakan hasil dari 4 × 5", answer: "20", difficulty: "Sedang", category: "Tangkap Angka" },
    { id: "ta8", question: "Tangkap angka yang merupakan hasil dari 36 ÷ 6", answer: "6", difficulty: "Sedang", category: "Tangkap Angka" },
    { id: "ta9", question: "Tangkap angka yang merupakan hasil dari 25 + 15", answer: "40", difficulty: "Sedang", category: "Tangkap Angka" },
    { id: "ta10", question: "Tangkap angka yang merupakan hasil dari 50 - 25", answer: "25", difficulty: "Sedang", category: "Tangkap Angka" },
    { id: "ta11", question: "Tangkap angka yang merupakan hasil dari 7 × 8", answer: "56", difficulty: "Sulit", category: "Tangkap Angka" },
    { id: "ta12", question: "Tangkap angka yang merupakan hasil dari 100 ÷ 5", answer: "20", difficulty: "Sedang", category: "Tangkap Angka" },
  ],

  "memory-card": [
    { id: "mc1", question: "Cocokkan kartu dengan pasangan yang benar: Matahari", answer: "Cahaya", difficulty: "Mudah", category: "Memory Card" },
    { id: "mc2", question: "Cocokkan kartu dengan pasangan yang benar: Bulan", answer: "Malam", difficulty: "Mudah", category: "Memory Card" },
    { id: "mc3", question: "Cocokkan kartu dengan pasangan yang benar: Api", answer: "Panas", difficulty: "Mudah", category: "Memory Card" },
    { id: "mc4", question: "Cocokkan kartu dengan pasangan yang benar: Air", answer: "Dingin", difficulty: "Sedang", category: "Memory Card" },
    { id: "mc5", question: "Cocokkan kartu dengan pasangan yang benar: Pohon", answer: "Daun", difficulty: "Mudah", category: "Memory Card" },
    { id: "mc6", question: "Cocokkan kartu dengan pasangan yang benar: Hujan", answer: "Awan", difficulty: "Sedang", category: "Memory Card" },
    { id: "mc7", question: "Cocokkan kartu dengan pasangan yang benar: Mata", answer: "Melihat", difficulty: "Sedang", category: "Memory Card" },
    { id: "mc8", question: "Cocokkan kartu dengan pasangan yang benar: Telinga", answer: "Mendengar", difficulty: "Sedang", category: "Memory Card" },
    { id: "mc9", question: "Cocokkan kartu dengan pasangan yang benar: Pensil", answer: "Tulis", difficulty: "Sedang", category: "Memory Card" },
    { id: "mc10", question: "Cocokkan kartu dengan pasangan yang benar: Buku", answer: "Baca", difficulty: "Sedang", category: "Memory Card" },
    { id: "mc11", question: "Cocokkan kartu dengan pasangan yang benar: Gitar", answer: "Petal", difficulty: "Sulit", category: "Memory Card" },
    { id: "mc12", question: "Cocokkan kartu dengan pasangan yang benar: Pensil Warna", answer: "Gambar", difficulty: "Sulit", category: "Memory Card" },
  ],

  "maze-edukasi": [
    { id: "me1", question: "Jalur mana yang benar untuk sampai ke sekolah? (A) Kiri (B) Kanan (C) Lurus (D) Putar balik", options: ["Kiri", "Kanan", "Lurus", "Putar balik"], answer: "Kanan", difficulty: "Mudah", category: "Maze Edukasi" },
    { id: "me2", question: "Untuk ke perpustakaan, ambil jalan yang mana? (A) Atas (B) Bawah (C) Kiri (D) Kanan", options: ["Atas", "Bawah", "Kiri", "Kanan"], answer: "Atas", difficulty: "Mudah", category: "Maze Edukasi" },
    { id: "me3", question: "Cara tercepat ke rumah sakit lewat mana? (A) Jalan utama (B) Jalan kecil (C) Jalan tol (D) Jalan setapak", options: ["Jalan utama", "Jalan kecil", "Jalan tol", "Jalan setapak"], answer: "Jalan utama", difficulty: "Mudah", category: "Maze Edukasi" },
    { id: "me4", question: "Untuk ke taman bermain, jalan yang benar adalah? (A) Belok kiri (B) Belok kanan (C) Lurus (D) Putar balik", options: ["Belok kiri", "Belok kanan", "Lurus", "Putar balik"], answer: "Belok kanan", difficulty: "Sedang", category: "Maze Edukasi" },
    { id: "me5", question: "Jalur mana yang menghindari rintangan? (A) Atas (B) Bawah (C) Kiri (D) Kanan", options: ["Atas", "Bawah", "Kiri", "Kanan"], answer: "Bawah", difficulty: "Sedang", category: "Maze Edukasi" },
    { id: "me6", question: "Ke mana harus berbelok untuk ke kantor pos? (A) Kiri (B) Kanan (C) Lurus (D) Putar balik", options: ["Kiri", "Kanan", "Lurus", "Putar balik"], answer: "Kiri", difficulty: "Sedang", category: "Maze Edukasi" },
    { id: "me7", question: "Untuk mencapai tujuan, pilih jalur mana? (A) A (B) B (C) C (D) D", options: ["A", "B", "C", "D"], answer: "B", difficulty: "Sedang", category: "Maze Edukasi" },
    { id: "me8", question: "Jalur yang paling pendek ke toko lewat mana? (A) Via taman (B) Via jalan raya (C) Via gang (D) Via jembatan", options: ["Via taman", "Via jalan raya", "Via gang", "Via jembatan"], answer: "Via jalan raya", difficulty: "Sedang", category: "Maze Edukasi" },
    { id: "me9", question: "Ke pintu keluar harus lewat mana? (A) Utara (B) Selatan (C) Timur (D) Barat", options: ["Utara", "Selatan", "Timur", "Barat"], answer: "Utara", difficulty: "Sulit", category: "Maze Edukasi" },
    { id: "me10", question: "Jalur yang aman dari rintangan air adalah? (A) Kiri (B) Kanan (C) Atas (D) Bawah", options: ["Kiri", "Kanan", "Atas", "Bawah"], answer: "Atas", difficulty: "Sulit", category: "Maze Edukasi" },
    { id: "me11", question: "Untuk ke perpustakaan kota, belok ke mana? (A) Kiri (B) Kanan (C) Lurus (D) U-turn", options: ["Kiri", "Kanan", "Lurus", "U-turn"], answer: "Kanan", difficulty: "Sedang", category: "Maze Edukasi" },
    { id: "me12", question: "Jalur mana yang menghindari kemacetan? (A) Jalan atas (B) Jalan bawah (C) Jalan samping (D) Jalan belakang", options: ["Jalan atas", "Jalan bawah", "Jalan samping", "Jalan belakang"], answer: "Jalan samping", difficulty: "Sulit", category: "Maze Edukasi" },
  ],

  "quiz-ipa": [
    { id: "qi1", question: "Planet terdekat dari Matahari adalah?", options: ["Merkurius", "Venus", "Bumi", "Mars"], answer: "Merkurius", difficulty: "Mudah", category: "IPA" },
    { id: "qi2", question: "Air membeku pada suhu?", options: ["100°C", "50°C", "0°C", "-10°C"], answer: "0°C", difficulty: "Mudah", category: "IPA" },
    { id: "qi3", question: "Hewan yang bisa berubah warna adalah?", options: ["Buaya", "Bunglon", "Ular", "Katak"], answer: "Bunglon", difficulty: "Mudah", category: "IPA" },
    { id: "qi4", question: "Bagian tumbuhan yang menyerap air adalah?", options: ["Daun", "Akar", "Batang", "Bunga"], answer: "Akar", difficulty: "Mudah", category: "IPA" },
    { id: "qi5", question: "Sumber cahaya terdekat dari Bumi adalah?", options: ["Bulan", "Matahari", "Bintang", "Venus"], answer: "Matahari", difficulty: "Sedang", category: "IPA" },
    { id: "qi6", question: "Proses berubahnya air menjadi uap disebut?", options: ["Mengkristal", "Menguap", "Mengembun", "Mencair"], answer: "Menguap", difficulty: "Sedang", category: "IPA" },
    { id: "qi7", question: "Organ tubuh yang berfungsi memompa darah adalah?", options: ["Paru-paru", "Hati", "Jantung", "Ginjal"], answer: "Jantung", difficulty: "Mudah", category: "IPA" },
    { id: "qi8", question: "Hewan yang termasuk golongan amfibi adalah?", options: ["Ikan", "Katak", "Burung", "Ular"], answer: "Katak", difficulty: "Sedang", category: "IPA" },
    { id: "qi9", question: "Lapisan atmosfer yang melindungi dari radiasi UV adalah?", options: ["Troposfer", "Stratosfer", "Mesosfer", "Termosfer"], answer: "Stratosfer", difficulty: "Sulit", category: "IPA" },
    { id: "qi10", question: "Gas yang paling banyak di atmosfer Bumi adalah?", options: ["Oksigen", "Karbon dioksida", "Nitrogen", "Hidrogen"], answer: "Nitrogen", difficulty: "Sedang", category: "IPA" },
    { id: "qi11", question: "Proses fotosintesis menghasilkan?", options: ["CO2", "H2O", "Oksigen", "Nitrogen"], answer: "Oksigen", difficulty: "Sedang", category: "IPA" },
    { id: "qi12", question: "Planet terbesar di tata surya adalah?", options: ["Saturnus", "Jupiter", "Neptunus", "Uranus"], answer: "Jupiter", difficulty: "Sedang", category: "IPA" },
  ],

  "quiz-ips": [
    { id: "qi1", question: "Ibukota Indonesia adalah?", options: ["Bandung", "Surabaya", "Jakarta", "Yogyakarta"], answer: "Jakarta", difficulty: "Mudah", category: "IPS" },
    { id: "qi2", question: "Pahlawan nasional yang dikenal sebagai Bapik Pendidikan adalah?", options: ["Soekarno", "Ki Hajar Dewantara", "Diponegoro", "Sudirman"], answer: "Ki Hajar Dewantara", difficulty: "Sedang", category: "IPS" },
    { id: "qi3", question: "Sungai terpanjang di Indonesia adalah?", options: ["Sungai Kapuas", "Sungai Mahakam", "Sungai Barito", "Sungai Musi"], answer: "Sungai Kapuas", difficulty: "Sedang", category: "IPS" },
    { id: "qi4", question: "Pulau terbesar di Indonesia adalah?", options: ["Sumatera", "Jawa", "Kalimantan", "Sulawesi"], answer: "Kalimantan", difficulty: "Sedang", category: "IPS" },
    { id: "qi5", question: "Bendera Indonesia memiliki warna?", options: ["Merah Putih", "Merah Biru", "Kuning Hijau", "Putih Biru"], answer: "Merah Putih", difficulty: "Mudah", category: "IPS" },
    { id: "qi6", question: "Proklamasi kemerdekaan Indonesia terjadi pada tanggal?", options: ["17 Agustus 1945", "17 Agustus 1950", "1 Juni 1945", "28 Oktober 1928"], answer: "17 Agustus 1945", difficulty: "Sedang", category: "IPS" },
    { id: "qi7", question: "Mata uang Indonesia adalah?", options: ["Dollar", "Rupiah", "Ringgit", "Yen"], answer: "Rupiah", difficulty: "Mudah", category: "IPS" },
    { id: "qi8", question: "Laut yang memisahkan Indonesia dengan Australia adalah?", options: ["Laut Jawa", "Laut Banda", "Laut Timor", "Laut Arafuru"], answer: "Laut Timor", difficulty: "Sulit", category: "IPS" },
    { id: "qi9", question: "Gunung tertinggi di Indonesia adalah?", options: ["Gunung Merapi", "Gunung Kerinci", "Gunung Jaya Wijaya", "Gunung Semeru"], answer: "Gunung Jaya Wijaya", difficulty: "Sedang", category: "IPS" },
    { id: "qi10", question: "Negara tetangga Indonesia di sebelah utara adalah?", options: ["Australia", "Malaysia", "Filipina", "Timor Leste"], answer: "Malaysia", difficulty: "Mudah", category: "IPS" },
    { id: "qi11", question: "Hari kemerdekaan Indonesia dirayakan setiap?", options: ["17 Agustus", "1 Juni", "28 Oktober", "20 Mei"], answer: "17 Agustus", difficulty: "Mudah", category: "IPS" },
    { id: "qi12", question: "Jumlah provinsi di Indonesia saat ini adalah?", options: ["34", "33", "38", "40"], answer: "38", difficulty: "Sulit", category: "IPS" },
  ],

  "quiz-bahasa-indonesia": [
    { id: "qbi1", question: "Kata 'indah' merupakan kata?", options: ["Kata Kerja", "Kata Benda", "Kata Sifat", "Kata Keterangan"], answer: "Kata Sifat", difficulty: "Mudah", category: "Bahasa Indonesia" },
    { id: "qbi2", question: "Lawan kata dari 'besar' adalah?", options: ["Lebar", "Panjang", "Kecil", "Tinggi"], answer: "Kecil", difficulty: "Mudah", category: "Bahasa Indonesia" },
    { id: "qbi3", question: "Kata 'kami' termasuk kata ganti?", options: ["Orang Pertama Tunggal", "Orang Pertama Jamak", "Orang Kedua", "Orang Ketiga"], answer: "Orang Pertama Jamak", difficulty: "Sedang", category: "Bahasa Indonesia" },
    { id: "qbi4", question: "Antonim dari 'bahagia' adalah?", options: ["Gembira", "Sedih", "Senang", "Tertawa"], answer: "Sedih", difficulty: "Mudah", category: "Bahasa Indonesia" },
    { id: "qbi5", question: "Kata 'di' dalam kalimat 'Buku dibaca oleh anak' adalah?", options: ["Kata Depan", "Kata Penghubung", "Kata Kerja Pasif", "Keterangan"], answer: "Kata Kerja Pasif", difficulty: "Sedang", category: "Bahasa Indonesia" },
    { id: "qbi6", question: "Sinonim dari 'ramah' adalah?", options: ["Kasar", "Baik", "Santai", "Galak"], answer: "Baik", difficulty: "Mudah", category: "Bahasa Indonesia" },
    { id: "qbi7", question: "Kata 'sangat' dalam kalimat 'Sangat cantik' berfungsi sebagai?", options: ["Kata Benda", "Kata Kerja", "Kata Keterangan", "Kata Sifat"], answer: "Kata Keterangan", difficulty: "Sedang", category: "Bahasa Indonesia" },
    { id: "qbi8", question: "Imbuhan yang tepat untuk kata 'ajar' menjadi 'belajar' adalah?", options: ["Me- -an", "Ber-", "Ke- -an", "Pe- -an"], answer: "Ber-", difficulty: "Sedang", category: "Bahasa Indonesia" },
    { id: "qbi9", question: "Kata 'mereka' adalah kata ganti orang?", options: ["Pertama", "Kedua", "Ketiga", "Keempat"], answer: "Ketiga", difficulty: "Mudah", category: "Bahasa Indonesia" },
    { id: "qbi10", question: "Antonim dari 'tinggi' adalah?", options: ["Panjang", "Rendah", "Lebar", "Pendek"], answer: "Rendah", difficulty: "Mudah", category: "Bahasa Indonesia" },
    { id: "qbi11", question: "Kata 'anak-anak' termasuk bentuk jamak dari kata?", options: ["Anak", "Anaknya", "Anakan", "Keanak"], answer: "Anak", difficulty: "Mudah", category: "Bahasa Indonesia" },
    { id: "qbi12", question: "Kalimat yang memiliki subjek dan predikat yang lengkap disebut?", options: ["Kalimat Imperatif", "Kalimat Deklaratif", "Kalimat Interogatif", "Kalimat Simplek"], answer: "Kalimat Deklaratif", difficulty: "Sulit", category: "Bahasa Indonesia" },
  ],

  "quiz-bahasa-inggris": [
    { id: "qbi1", question: "Apa arti kata 'Hello' dalam Bahasa Indonesia?", options: ["Selamat tinggal", "Selamat datang", "Terima kasih", "Halo"], answer: "Halo", difficulty: "Mudah", category: "Bahasa Inggris" },
    { id: "qbi2", question: "Kata 'Big' dalam Bahasa Indonesia berarti?", options: ["Kecil", "Besar", "Panjang", "Tinggi"], answer: "Besar", difficulty: "Mudah", category: "Bahasa Inggris" },
    { id: "qbi3", question: "Apa kata sifat untuk 'Water' dalam Bahasa Inggris?", options: ["Hot", "Cold", "Wet", "Dry"], answer: "Wet", difficulty: "Sedang", category: "Bahasa Inggris" },
    { id: "qbi4", question: "Kata 'Beautiful' berarti?", options: ["Buruk", "Cantik", "Tinggi", "Pendek"], answer: "Cantik", difficulty: "Mudah", category: "Bahasa Inggris" },
    { id: "qbi5", question: "Terjemahkan 'I love you' ke Bahasa Indonesia:", options: ["Aku benci kamu", "Aku cinta kamu", "Aku sayang kamu", "Aku suka kamu"], answer: "Aku cinta kamu", difficulty: "Sedang", category: "Bahasa Inggris" },
    { id: "qbi6", question: "Kata 'Teacher' berarti?", options: ["Murid", "Guru", "Dokter", "Polisi"], answer: "Guru", difficulty: "Mudah", category: "Bahasa Inggris" },
    { id: "qbi7", question: "Apa jamak dari 'Child'?", options: ["Childs", "Childes", "Children", "Childrens"], answer: "Children", difficulty: "Sedang", category: "Bahasa Inggris" },
    { id: "qbi8", question: "Kata 'Sun' berarti?", options: ["Bulan", "Bintang", "Matahari", "Awan"], answer: "Matahari", difficulty: "Mudah", category: "Bahasa Inggris" },
    { id: "qbi9", question: "Apa past tense dari kata 'Go'?", options: ["Goed", "Gone", "Went", "Going"], answer: "Went", difficulty: "Sedang", category: "Bahasa Inggris" },
    { id: "qbi10", question: "Kata 'Happy' berarti?", options: ["Sedih", "Marah", "Bahagia", "Takut"], answer: "Bahagia", difficulty: "Mudah", category: "Bahasa Inggris" },
    { id: "qbi11", question: "Terjemahkan 'Good morning' ke Bahasa Indonesia:", options: ["Selamat malam", "Selamat pagi", "Selamat siang", "Selamat sore"], answer: "Selamat pagi", difficulty: "Mudah", category: "Bahasa Inggris" },
    { id: "qbi12", question: "Kata 'Fish' berarti?", options: ["Burung", "Ikan", "Kucing", "Anjing"], answer: "Ikan", difficulty: "Mudah", category: "Bahasa Inggris" },
  ],

  "susun-cerita": [
    { id: "sc1", question: "Susun kata-kata ini menjadi cerita: 'Anak / pergi / sekolah / ke / setiap / hari'", answer: "Anak pergi ke sekolah setiap hari", difficulty: "Mudah", category: "Susun Cerita" },
    { id: "sc2", question: "Susun kata-kata ini menjadi cerita: 'Ibu / memasak / dapur / di / nasi'", answer: "Ibu memasak nasi di dapur", difficulty: "Mudah", category: "Susun Cerita" },
    { id: "sc3", question: "Susun kata-kata ini menjadi cerita: 'Kucing / tidur / bantal / di / atas'", answer: "Kucing tidur di atas bantal", difficulty: "Mudah", category: "Susun Cerita" },
    { id: "sc4", question: "Susun kata-kata ini menjadi cerita: 'Hujan / turun / lebat / sangat / kemarin'", answer: "Hujan turun sangat lebat kemarin", difficulty: "Sedang", category: "Susun Cerita" },
    { id: "sc5", question: "Susun kata-kata ini menjadi cerita: 'Guru / mengajar / kelas / di / siswa / dengan'", answer: "Guru mengajar siswa di kelas", difficulty: "Sedang", category: "Susun Cerita" },
    { id: "sc6", question: "Susun kata-kata ini menjadi cerita: 'Ayah / ke / pergi / kerja / pagi / setiap'", answer: "Ayah pergi ke kerja setiap pagi", difficulty: "Sedang", category: "Susun Cerita" },
    { id: "sc7", question: "Susun kata-kata ini menjadi cerita: 'Adik / membaca / buku / cerita / sedang'", answer: "Adik sedang membaca buku cerita", difficulty: "Sedang", category: "Susun Cerita" },
    { id: "sc8", question: "Susun kata-kata ini menjadi cerita: 'Anak-anak / bermain / taman / di / berlari'", answer: "Anak-anak berlari bermain di taman", difficulty: "Sedang", category: "Susun Cerita" },
    { id: "sc9", question: "Susun kata-kata ini menjadi cerita: 'Kami / berwisata / danau / ke / musim / kemarin / liburan'", answer: "Kami berwisata ke danau kemarin liburan musim", difficulty: "Sulit", category: "Susun Cerita" },
    { id: "sc10", question: "Susun kata-kata ini menjadi cerita: 'Pelajar / belajar / untuk / ujian / tekun / harus'", answer: "Pelajar harus tekun belajar untuk ujian", difficulty: "Sulit", category: "Susun Cerita" },
    { id: "sc11", question: "Susun kata-kata ini menjadi cerita: 'Burung / terbang / langit / di / tinggi'", answer: "Burung terbang tinggi di langit", difficulty: "Mudah", category: "Susun Cerita" },
    { id: "sc12", question: "Susun kata-kata ini menjadi cerita: 'Siswa / presentasi / kelas / di / mempresentasikan / hasil / tugas'", answer: "Siswa mempresentasikan hasil tugas di kelas", difficulty: "Sulit", category: "Susun Cerita" },
  ],

  "cari-kata": [
    { id: "ck1", question: "Kata tersembunyi dalam 'Saya pergi ke SEKOLAH' adalah?", options: ["Sekolah", "Kolam", "Lahar", "Seka"], answer: "Sekolah", difficulty: "Mudah", category: "Cari Kata" },
    { id: "ck2", question: "Kata tersembunyi dalam 'Buku ini sangat BAGUS' adalah?", options: ["Bagus", "Gus", "Bus", "Bag"], answer: "Bagus", difficulty: "Mudah", category: "Cari Kata" },
    { id: "ck3", question: "Kata tersembunyi dalam 'Matahari bersinar CERAH' adalah?", options: ["Cerah", "Rah", "Cer", "Era"], answer: "Cerah", difficulty: "Mudah", category: "Cari Kata" },
    { id: "ck4", question: "Kata tersembunyi dalam 'Anak-anak bermain DI TAMAN' adalah?", options: ["Taman", "Man", "Tam", "Tama"], answer: "Taman", difficulty: "Sedang", category: "Cari Kata" },
    { id: "ck5", question: "Kata tersembunyi dalam 'Guru mengajar dengan SABAR' adalah?", options: ["Sabar", "Bar", "Sab", "Saba"], answer: "Sabar", difficulty: "Sedang", category: "Cari Kata" },
    { id: "ck6", question: "Kata tersembunyi dalam 'Air mengalir ke SUNGAI' adalah?", options: ["Sungai", "Ngai", "Sun", "Gai"], answer: "Sungai", difficulty: "Mudah", category: "Cari Kata" },
    { id: "ck7", question: "Kata tersembunyi dalam 'Rumah baru sangat INDAH' adalah?", options: ["Indah", "Dah", "Ind", "Inda"], answer: "Indah", difficulty: "Mudah", category: "Cari Kata" },
    { id: "ck8", question: "Kata tersembunyi dalam 'Ibu memasak NASI GORENG' adalah?", options: ["Nasi", "Goreng", "Gore", "Nas"], answer: "Nasi", difficulty: "Sedang", category: "Cari Kata" },
    { id: "ck9", question: "Kata tersembunyi dalam 'Pohon tinggi di HUTAN' adalah?", options: ["Hutan", "Tan", "Hu", "Huta"], answer: "Hutan", difficulty: "Sedang", category: "Cari Kata" },
    { id: "ck10", question: "Kata tersembunyi dalam 'Pelajar harus RAJIN belajar' adalah?", options: ["Rajin", "Jin", "Ra", "Raji"], answer: "Rajin", difficulty: "Sedang", category: "Cari Kata" },
    { id: "ck11", question: "Kata tersembunyi dalam 'Burung terbang di AWAN' adalah?", options: ["Awan", "Wan", "Aw", "Awa"], answer: "Awan", difficulty: "Mudah", category: "Cari Kata" },
    { id: "ck12", question: "Kata tersembunyi dalam 'Siswa belajar dengan TEKUN' adalah?", options: ["Tekun", "Kun", "Tek", "Teku"], answer: "Tekun", difficulty: "Sedang", category: "Cari Kata" },
  ],

  "tebak-profesi": [
    { id: "tp1", question: "Orang yang mengajar di sekolah disebut?", options: ["Dokter", "Guru", "Polisi", "Tentara"], answer: "Guru", difficulty: "Mudah", category: "Tebak Profesi" },
    { id: "tp2", question: "Orang yang memeriksa kesehatan disebut?", options: ["Guru", "Dokter", "Perawat", "Apoteker"], answer: "Dokter", difficulty: "Mudah", category: "Tebak Profesi" },
    { id: "tp3", question: "Orang yang memadamkan kebakaran disebut?", options: ["Polisi", "Tentara", "Pemadam", "Sopir"], answer: "Pemadam", difficulty: "Mudah", category: "Tebak Profesi" },
    { id: "tp4", question: "Orang yang menerbangkan pesawat disebut?", options: ["Kapten", "Pilot", "Teknisi", "Pramugari"], answer: "Pilot", difficulty: "Mudah", category: "Tebak Profesi" },
    { id: "tp5", question: "Orang yang bekerja di dapur restoran disebut?", options: ["Pramusaji", "Koki", "Manajer", "Kasir"], answer: "Koki", difficulty: "Sedang", category: "Tebak Profesi" },
    { id: "tp6", question: "Orang yang menanam padi disebut?", options: ["Nelayan", "Petani", "Pedagang", "Pekerja"], answer: "Petani", difficulty: "Mudah", category: "Tebak Profesi" },
    { id: "tp7", question: "Orang yang menangkap ikan disebut?", options: ["Petani", "Nelayan", "Pedagang", "Buruh"], answer: "Nelayan", difficulty: "Mudah", category: "Tebak Profesi" },
    { id: "tp8", question: "Orang yang menulis berita disebut?", options: ["Guru", "Penulis", "Jurnalis", "Editor"], answer: "Jurnalis", difficulty: "Sedang", category: "Tebak Profesi" },
    { id: "tp9", question: "Orang yang mengendarai bus disebut?", options: ["Pilot", "Sopir", "Kondektur", "Penumpang"], answer: "Sopir", difficulty: "Mudah", category: "Tebak Profesi" },
    { id: "tp10", question: "Orang yang menjaga keamanan disebut?", options: ["Dokter", "Polisi", "Guru", "Tukang"], answer: "Polisi", difficulty: "Mudah", category: "Tebak Profesi" },
    { id: "tp11", question: "Orang yang bekerja di toko obat disebut?", options: ["Dokter", "Perawat", "Apoteker", "Bidan"], answer: "Apoteker", difficulty: "Sedang", category: "Tebak Profesi" },
    { id: "tp12", question: "Orang yang menggambar bangunan disebut?", options: ["Insinyur", "Arsitek", "Tukang", "Kontraktor"], answer: "Arsitek", difficulty: "Sedang", category: "Tebak Profesi" },
  ],

  "tebak-hewan": [
    { id: "the1", question: "Hewan apa yang suka makan bambu?", options: ["Singa", "Gajah", "Panda", "Kuda"], answer: "Panda", difficulty: "Mudah", category: "Tebak Hewan" },
    { id: "the2", question: "Hewan apa yang bisa melompat tinggi?", options: ["Kucing", "Kanguru", "Sapi", "Kambing"], answer: "Kanguru", difficulty: "Mudah", category: "Tebak Hewan" },
    { id: "the3", question: "Hewan apa yang mengaum keras?", options: ["Kucing", "Anjing", "Singa", "Kelinci"], answer: "Singa", difficulty: "Mudah", category: "Tebak Hewan" },
    { id: "the4", question: "Hewan apa yang bisa terbang?", options: ["Ikan", "Kodok", "Burung", "Ular"], answer: "Burung", difficulty: "Mudah", category: "Tebak Hewan" },
    { id: "the5", question: "Hewan apa yang memiliki belalai panjang?", options: ["Badak", "Gajah", "Jerapah", "Kuda Nil"], answer: "Gajah", difficulty: "Mudah", category: "Tebak Hewan" },
    { id: "the6", question: "Hewan apa yang suka hidup di air?", options: ["Kucing", "Anjing", "Ikan", "Ayam"], answer: "Ikan", difficulty: "Mudah", category: "Tebak Hewan" },
    { id: "the7", question: "Hewan apa yang memiliki leher panjang?", options: ["Gajah", "Jerapah", "Kuda", "Sapi"], answer: "Jerapah", difficulty: "Mudah", category: "Tebak Hewan" },
    { id: "the8", question: "Hewan apa yang suka bersembunyi di tanah?", options: ["Burung", "Ular", "Ikan", "Kucing"], answer: "Ular", difficulty: "Sedang", category: "Tebak Hewan" },
    { id: "the9", question: "Hewan apa yang bisa berubah warna?", options: ["Kucing", "Anjing", "Bunglon", "Kelinci"], answer: "Bunglon", difficulty: "Sedang", category: "Tebak Hewan" },
    { id: "the10", question: "Hewan apa yang suka makan rumput?", options: ["Kucing", "Anjing", "Sapi", "Ayam"], answer: "Sapi", difficulty: "Mudah", category: "Tebak Hewan" },
    { id: "the11", question: "Hewan apa yang suka berenang di laut?", options: ["Kuda", "Sapi", "Paus", "Ayam"], answer: "Paus", difficulty: "Sedang", category: "Tebak Hewan" },
    { id: "the12", question: "Hewan apa yang bisa menarik gerbong?", options: ["Kuda", "Sapi", "Gajah", "Kerbau"], answer: "Gajah", difficulty: "Sedang", category: "Tebak Hewan" },
  ],

  "tebak-pahlawan": [
    { id: "tph1", question: "Siapa pahlawan yang dikenal sebagai Proklamator?", options: ["Diponegoro", "Sudirman", "Soekarno", "Hatta"], answer: "Soekarno", difficulty: "Mudah", category: "Tebak Pahlawan" },
    { id: "tph2", question: "Siapa pahlawan yang dikenal sebagai Bapak Pendidikan?", options: ["Soekarno", "Ki Hajar Dewantara", "Sudirman", "Diponegoro"], answer: "Ki Hajar Dewantara", difficulty: "Mudah", category: "Tebak Pahlawan" },
    { id: "tph3", question: "Siapa pahlawan yang memimpin perang gerilya?", options: ["Diponegoro", "Sudirman", "Soekarno", "Hatta"], answer: "Sudirman", difficulty: "Sedang", category: "Tebak Pahlawan" },
    { id: "tph4", question: "Siapa pahlawan yang dikenal sebagai Pangeran Diponegoro?", options: ["Soekarno", "Diponegoro", "Sudirman", "Imam Bonjol"], answer: "Diponegoro", difficulty: "Mudah", category: "Tebak Pahlawan" },
    { id: "tph5", question: "Siapa pahlawan yang memperjuangkan kemerdekaan di Aceh?", options: ["Imam Bonjol", "Sudirman", "Soekarno", "Diponegoro"], answer: "Imam Bonjol", difficulty: "Sedang", category: "Tebak Pahlawan" },
    { id: "tph6", question: "Siapa pahlawan yang dikenal sebagai Pattimura?", options: ["Soekarno", "Pattimura", "Sudirman", "Diponegoro"], answer: "Pattimura", difficulty: "Mudah", category: "Tebak Pahlawan" },
    { id: "tph7", question: "Siapa pahlawan wanita yang dikenal sebagai Kartini?", options: ["Martha", "Kartini", "Dewi", "Siti"], answer: "Kartini", difficulty: "Mudah", category: "Tebak Pahlawan" },
    { id: "tph8", question: "Siapa pahlawan yang memimpin perang di Surabaya?", options: ["Bung Tomo", "Sudirman", "Soekarno", "Diponegoro"], answer: "Bung Tomo", difficulty: "Sedang", category: "Tebak Pahlawan" },
    { id: "tph9", question: "Siapa pahlawan yang dikenal sebagai Cut Nyak Dien?", options: ["Kartini", "Cut Nyak Dien", "Martha", "Ratna"], answer: "Cut Nyak Dien", difficulty: "Sedang", category: "Tebak Pahlawan" },
    { id: "tph10", question: "Siapa pahlawan yang memperjuangkan kemerdekaan di Bali?", options: ["I Gusti Ngurah Rai", "Sudirman", "Soekarno", "Diponegoro"], answer: "I Gusti Ngurah Rai", difficulty: "Sulit", category: "Tebak Pahlawan" },
    { id: "tph11", question: "Siapa pahlawan yang dikenal sebagai Sultan Agung?", options: ["Soekarno", "Sultan Agung", "Diponegoro", "Sudirman"], answer: "Sultan Agung", difficulty: "Sulit", category: "Tebak Pahlawan" },
    { id: "tph12", question: "Siapa pahlawan yang memimpin perang Padri?", options: ["Tuanku Imam Bonjol", "Diponegoro", "Sudirman", "Soekarno"], answer: "Tuanku Imam Bonjol", difficulty: "Sulit", category: "Tebak Pahlawan" },
  ],

  "tebak-provinsi": [
    { id: "tpv1", question: "Ibukota provinsi Jawa Barat adalah?", options: ["Semarang", "Bandung", "Surabaya", "Yogyakarta"], answer: "Bandung", difficulty: "Mudah", category: "Tebak Provinsi" },
    { id: "tpv2", question: "Ibukota provinsi DKI Jakarta adalah?", options: ["Jakarta", "Bandung", "Semarang", "Surabaya"], answer: "Jakarta", difficulty: "Mudah", category: "Tebak Provinsi" },
    { id: "tpv3", question: "Ibukota provinsi Jawa Tengah adalah?", options: ["Yogyakarta", "Semarang", "Surabaya", "Bandung"], answer: "Semarang", difficulty: "Mudah", category: "Tebak Provinsi" },
    { id: "tpv4", question: "Ibukota provinsi Jawa Timur adalah?", options: ["Semarang", "Bandung", "Surabaya", "Malang"], answer: "Surabaya", difficulty: "Mudah", category: "Tebak Provinsi" },
    { id: "tpv5", question: "Ibukota provinsi Bali adalah?", options: ["Denpasar", "Singaraja", "Gianyar", "Tabanan"], answer: "Denpasar", difficulty: "Mudah", category: "Tebak Provinsi" },
    { id: "tpv6", question: "Ibukota provinsi Sumatera Utara adalah?", options: ["Medan", "Padang", "Palembang", "Lampung"], answer: "Medan", difficulty: "Sedang", category: "Tebak Provinsi" },
    { id: "tpv7", question: "Ibukota provinsi Kalimantan Timur adalah?", options: ["Banjarmasin", "Samarinda", "Pontianak", "Balikpapan"], answer: "Samarinda", difficulty: "Sedang", category: "Tebak Provinsi" },
    { id: "tpv8", question: "Ibukota provinsi Sulawesi Selatan adalah?", options: ["Manado", "Makassar", "Palu", "Gorontalo"], answer: "Makassar", difficulty: "Sedang", category: "Tebak Provinsi" },
    { id: "tpv9", question: "Ibukota provinsi Papua adalah?", options: ["Jayapura", "Sorong", "Merauke", "Timika"], answer: "Jayapura", difficulty: "Sedang", category: "Tebak Provinsi" },
    { id: "tpv10", question: "Ibukota provinsi Nusa Tenggara Barat adalah?", options: ["Kupang", "Mataram", "Denpasar", "Bima"], answer: "Mataram", difficulty: "Sedang", category: "Tebak Provinsi" },
    { id: "tpv11", question: "Ibukota provinsi Aceh adalah?", options: ["Banda Aceh", "Medan", "Padang", "Pekanbaru"], answer: "Banda Aceh", difficulty: "Sedang", category: "Tebak Provinsi" },
    { id: "tpv12", question: "Ibukota provinsi Sumatera Barat adalah?", options: ["Medan", "Padang", "Palembang", "Pekanbaru"], answer: "Padang", difficulty: "Sedang", category: "Tebak Provinsi" },
  ],

  "puzzle-peta-indonesia": [
    { id: "ppi1", question: "Pulau mana yang berbentuk seperti huruf 'K'?", options: ["Sumatera", "Jawa", "Kalimantan", "Sulawesi"], answer: "Sulawesi", difficulty: "Mudah", category: "Puzzle Peta Indonesia" },
    { id: "ppi2", question: "Pulau mana yang terletak di sebelah barat Indonesia?", options: ["Jawa", "Sumatera", "Kalimantan", "Sulawesi"], answer: "Sumatera", difficulty: "Mudah", category: "Puzzle Peta Indonesia" },
    { id: "ppi3", question: "Pulau mana yang terletak di sebelah timur Indonesia?", options: ["Papua", "Sumatera", "Jawa", "Kalimantan"], answer: "Papua", difficulty: "Mudah", category: "Puzzle Peta Indonesia" },
    { id: "ppi4", question: "Pulau mana yang terbesar kedua di Indonesia?", options: ["Jawa", "Sumatera", "Kalimantan", "Sulawesi"], answer: "Sumatera", difficulty: "Sedang", category: "Puzzle Peta Indonesia" },
    { id: "ppi5", question: "Pulau mana yang memiliki banyak gunung berapi aktif?", options: ["Kalimantan", "Sumatera", "Jawa", "Papua"], answer: "Jawa", difficulty: "Sedang", category: "Puzzle Peta Indonesia" },
    { id: "ppi6", question: "Pulau mana yang terletak di antara Jawa dan Kalimantan?", options: ["Bali", "Lombok", "Sumatera", "Sulawesi"], answer: "Bali", difficulty: "Sedang", category: "Puzzle Peta Indonesia" },
    { id: "ppi7", question: "Pulau mana yang memiliki danau terbesar di Indonesia?", options: ["Sumatera", "Jawa", "Kalimantan", "Sulawesi"], answer: "Sumatera", difficulty: "Sedang", category: "Puzzle Peta Indonesia" },
    { id: "ppi8", question: "Pulau mana yang terletak di sebelah utara Jawa?", options: ["Kalimantan", "Sumatera", "Sulawesi", "Papua"], answer: "Kalimantan", difficulty: "Sedang", category: "Puzzle Peta Indonesia" },
    { id: "ppi9", question: "Pulau mana yang memiliki bentuk menyerupai burung?", options: ["Sulawesi", "Kalimantan", "Sumatera", "Jawa"], answer: "Sulawesi", difficulty: "Sulit", category: "Puzzle Peta Indonesia" },
    { id: "ppi10", question: "Pulau mana yang merupakan pulau terkecil dari 5 pulau besar?", options: ["Bali", "Nusa Tenggara", "Maluku", "Papua"], answer: "Bali", difficulty: "Sedang", category: "Puzzle Peta Indonesia" },
    { id: "ppi11", question: "Pulau mana yang terletak di sebelah barat daya Jawa?", options: ["Sumatera", "Bali", "Nusa Tenggara Barat", "Kalimantan"], answer: "Sumatera", difficulty: "Sulit", category: "Puzzle Peta Indonesia" },
    { id: "ppi12", question: "Pulau mana yang terletak di sebelah timur Kalimantan?", options: ["Sulawesi", "Sumatera", "Jawa", "Papua"], answer: "Sulawesi", difficulty: "Sedang", category: "Puzzle Peta Indonesia" },
  ],

  "operasi-hitung-berantai": [
    { id: "ohb1", question: "5 + 3 - 2 = ?", options: ["6", "7", "5", "8"], answer: "6", difficulty: "Mudah", category: "Operasi Hitung Berantai" },
    { id: "ohb2", question: "10 - 4 + 2 = ?", options: ["8", "7", "6", "9"], answer: "8", difficulty: "Mudah", category: "Operasi Hitung Berantai" },
    { id: "ohb3", question: "3 × 2 + 4 = ?", options: ["10", "12", "14", "16"], answer: "10", difficulty: "Sedang", category: "Operasi Hitung Berantai" },
    { id: "ohb4", question: "20 ÷ 4 + 3 = ?", options: ["8", "7", "6", "9"], answer: "8", difficulty: "Sedang", category: "Operasi Hitung Berantai" },
    { id: "ohb5", question: "15 - 5 × 2 = ?", options: ["5", "20", "10", "0"], answer: "5", difficulty: "Sedang", category: "Operasi Hitung Berantai" },
    { id: "ohb6", question: "8 + 2 × 3 = ?", options: ["30", "14", "16", "12"], answer: "14", difficulty: "Sedang", category: "Operasi Hitung Berantai" },
    { id: "ohb7", question: "12 ÷ 3 + 5 = ?", options: ["9", "8", "7", "10"], answer: "9", difficulty: "Sedang", category: "Operasi Hitung Berantai" },
    { id: "ohb8", question: "7 × 2 - 6 = ?", options: ["8", "10", "12", "14"], answer: "8", difficulty: "Sedang", category: "Operasi Hitung Berantai" },
    { id: "ohb9", question: "25 - 10 ÷ 5 = ?", options: ["3", "23", "5", "15"], answer: "23", difficulty: "Sulit", category: "Operasi Hitung Berantai" },
    { id: "ohb10", question: "4 × 4 + 4 ÷ 2 = ?", options: ["18", "16", "14", "20"], answer: "18", difficulty: "Sulit", category: "Operasi Hitung Berantai" },
    { id: "ohb11", question: "100 - 50 + 25 = ?", options: ["75", "25", "50", "100"], answer: "75", difficulty: "Sedang", category: "Operasi Hitung Berantai" },
    { id: "ohb12", question: "9 × 3 - 12 ÷ 4 = ?", options: ["21", "24", "18", "15"], answer: "24", difficulty: "Sulit", category: "Operasi Hitung Berantai" },
  ],

  "simon-memory-edukasi": [
    { id: "sme1", question: "Tangkap urutan warna yang benar: Merah, Biru, Hijau", answer: "Merah Biru Hijau", difficulty: "Mudah", category: "Simon Memory Edukasi" },
    { id: "sme2", question: "Tangkap urutan warna yang benar: Kuning, Merah, Biru", answer: "Kuning Merah Biru", difficulty: "Mudah", category: "Simon Memory Edukasi" },
    { id: "sme3", question: "Tangkap urutan warna yang benar: Hijau, Kuning, Merah", answer: "Hijau Kuning Merah", difficulty: "Mudah", category: "Simon Memory Edukasi" },
    { id: "sme4", question: "Tangkap urutan warna yang benar: Biru, Hijau, Kuning, Merah", answer: "Biru Hijau Kuning Merah", difficulty: "Sedang", category: "Simon Memory Edukasi" },
    { id: "sme5", question: "Tangkap urutan warna yang benar: Merah, Biru, Hijau, Kuning", answer: "Merah Biru Hijau Kuning", difficulty: "Sedang", category: "Simon Memory Edukasi" },
    { id: "sme6", question: "Tangkap urutan warna yang benar: Kuning, Hijau, Biru, Merah", answer: "Kuning Hijau Biru Merah", difficulty: "Sedang", category: "Simon Memory Edukasi" },
    { id: "sme7", question: "Tangkap urutan warna yang benar: Hijau, Merah, Kuning, Biru", answer: "Hijau Merah Kuning Biru", difficulty: "Sedang", category: "Simon Memory Edukasi" },
    { id: "sme8", question: "Tangkap urutan warna yang benar: Biru, Merah, Hijau, Kuning", answer: "Biru Merah Hijau Kuning", difficulty: "Sedang", category: "Simon Memory Edukasi" },
    { id: "sme9", question: "Tangkap urutan warna yang benar: Merah, Kuning, Hijau, Biru, Merah", answer: "Merah Kuning Hijau Biru Merah", difficulty: "Sulit", category: "Simon Memory Edukasi" },
    { id: "sme10", question: "Tangkap urutan warna yang benar: Hijau, Biru, Kuning, Merah, Hijau", answer: "Hijau Biru Kuning Merah Hijau", difficulty: "Sulit", category: "Simon Memory Edukasi" },
    { id: "sme11", question: "Tangkap urutan warna yang benar: Kuning, Merah, Biru, Hijau, Kuning", answer: "Kuning Merah Biru Hijau Kuning", difficulty: "Sulit", category: "Simon Memory Edukasi" },
    { id: "sme12", question: "Tangkap urutan warna yang benar: Biru, Hijau, Merah, Kuning, Biru", answer: "Biru Hijau Merah Kuning Biru", difficulty: "Sulit", category: "Simon Memory Edukasi" },
  ],

  "roda-pintar": [
    { id: "rp1", question: "Roda mana yang berhenti di angka terbesar? Roda A: 5, Roda B: 8, Roda C: 3", options: ["Roda A", "Roda B", "Roda C", "Semua sama"], answer: "Roda B", difficulty: "Mudah", category: "Roda Pintar" },
    { id: "rp2", question: "Roda mana yang berhenti di warna Merah? Roda A: Biru, Roda B: Merah, Roda C: Hijau", options: ["Roda A", "Roda B", "Roda C", "Tidak ada"], answer: "Roda B", difficulty: "Mudah", category: "Roda Pintar" },
    { id: "rp3", question: "Roda mana yang berhenti di huruf 'A'? Roda A: B, Roda B: C, Roda C: A", options: ["Roda A", "Roda B", "Roda C", "Tidak ada"], answer: "Roda C", difficulty: "Mudah", category: "Roda Pintar" },
    { id: "rp4", question: "Roda mana yang berhenti di gambar buah? Roda A: Bintang, Roda B: Buah, Roda C: Hewan", options: ["Roda A", "Roda B", "Roda C", "Tidak ada"], answer: "Roda B", difficulty: "Sedang", category: "Roda Pintar" },
    { id: "rp5", question: "Roda mana yang berhenti di angka genap? Roda A: 7, Roda B: 9, Roda C: 4", options: ["Roda A", "Roda B", "Roda C", "Tidak ada"], answer: "Roda C", difficulty: "Sedang", category: "Roda Pintar" },
    { id: "rp6", question: "Roda mana yang berhenti di planet? Roda A: Bintang, Roda B: Awan, Roda C: Planet", options: ["Roda A", "Roda B", "Roda C", "Tidak ada"], answer: "Roda C", difficulty: "Sedang", category: "Roda Pintar" },
    { id: "rp7", question: "Roda mana yang berhenti di hewan terbang? Roda A: Ikan, Roda B: Burung, Roda C: Kucing", options: ["Roda A", "Roda B", "Roda C", "Tidak ada"], answer: "Roda B", difficulty: "Sedang", category: "Roda Pintar" },
    { id: "rp8", question: "Roda mana yang berhenti di alat musik? Roda A: Pensil, Roda B: Gitar, Roda C: Buku", options: ["Roda A", "Roda B", "Roda C", "Tidak ada"], answer: "Roda B", difficulty: "Sedang", category: "Roda Pintar" },
    { id: "rp9", question: "Roda mana yang berhenti di warna dingin? Roda A: Merah, Roda B: Oranye, Roda C: Biru", options: ["Roda A", "Roda B", "Roda C", "Tidak ada"], answer: "Roda C", difficulty: "Sedang", category: "Roda Pintar" },
    { id: "rp10", question: "Roda mana yang berhenti di angka prima? Roda A: 4, Roda B: 6, Roda C: 7", options: ["Roda A", "Roda B", "Roda C", "Tidak ada"], answer: "Roda C", difficulty: "Sulit", category: "Roda Pintar" },
    { id: "rp11", question: "Roda mana yang berhenti di benua? Roda A: Laut, Roda B: Gunung, Roda C: Benua", options: ["Roda A", "Roda B", "Roda C", "Tidak ada"], answer: "Roda C", difficulty: "Sedang", category: "Roda Pintar" },
    { id: "rp12", question: "Roda mana yang berhenti di alat transportasi udara? Roda A: Kapal, Roda B: Kereta, Roda C: Pesawat", options: ["Roda A", "Roda B", "Roda C", "Tidak ada"], answer: "Roda C", difficulty: "Sedang", category: "Roda Pintar" },
  ],
};
