export interface BudayaCategory {
  id: string;
  name: string;
  icon: string;
  emoji: string;
  description: string;
  color: string;
  gradient: string;
  href: string;
  gameCount: number;
  bgEmoji: string;
  decoration: string;
}

export const budayaCategories: BudayaCategory[] = [
  {
    id: "lagu-nasional",
    name: "Lagu Nasional",
    icon: "🎵",
    emoji: "🎵",
    description: "Lagu-lagu kebangsaan Indonesia",
    color: "red-400",
    gradient: "from-red-400 to-pink-500",
    href: "/budaya/lagu-nasional",
    gameCount: 2,
    bgEmoji: "🇮🇩",
    decoration: "Merah putih kebanggaan Indonesia",
  },
  {
    id: "lagu-daerah",
    name: "Lagu Daerah",
    icon: "🎼",
    emoji: "🎼",
    description: "Kekayaan musik daerah Nusantara",
    color: "blue-400",
    gradient: "from-blue-400 to-indigo-500",
    href: "/budaya/lagu-daerah",
    gameCount: 2,
    bgEmoji: "🎶",
    decoration: "Nada-nada indah dari seluruh Nusantara",
  },
  {
    id: "pakaian-adat",
    name: "Pakaian Adat",
    icon: "👘",
    emoji: "👘",
    description: "Ragam pakaian adat seluruh provinsi",
    color: "purple-400",
    gradient: "from-purple-400 to-pink-500",
    href: "/budaya/pakaian-adat",
    gameCount: 2,
    bgEmoji: "🪡",
    decoration: "Kain dan busana tradisional Indonesia",
  },
  {
    id: "rumah-adat",
    name: "Rumah Adat",
    icon: "🏠",
    emoji: "🏠",
    description: "Arsitektur tradisional Indonesia",
    color: "amber-400",
    gradient: "from-amber-400 to-orange-500",
    href: "/budaya/rumah-adat",
    gameCount: 2,
    bgEmoji: "🏘️",
    decoration: "Rumah-rumah adat dari sabang sampai merauke",
  },
  {
    id: "alat-musik",
    name: "Alat Musik Tradisional",
    icon: "🪕",
    emoji: "🪕",
    description: "Alat musik Nusantara",
    color: "green-400",
    gradient: "from-green-400 to-emerald-500",
    href: "/budaya/alat-musik",
    gameCount: 2,
    bgEmoji: "🥁",
    decoration: "Gamelan, angklung, dan alat musik lainnya",
  },
  {
    id: "tari-tradisional",
    name: "Tari Tradisional",
    icon: "💃",
    emoji: "💃",
    description: "Tarian tradisional daerah",
    color: "pink-400",
    gradient: "from-pink-400 to-rose-500",
    href: "/budaya/tari-tradisional",
    gameCount: 2,
    bgEmoji: "🪭",
    decoration: "Gerakan tari yang anggun dari seluruh Nusantara",
  },
  {
    id: "senjata-tradisional",
    name: "Senjata Tradisional",
    icon: "🥁",
    emoji: "🥁",
    description: "Senjata adat Nusantara",
    color: "slate-400",
    gradient: "from-slate-400 to-gray-600",
    href: "/budaya/senjata-tradisional",
    gameCount: 2,
    bgEmoji: "⚔️",
    decoration: "Keris, mandau, dan senjata adat lainnya",
  },
  {
    id: "makanan-khas",
    name: "Makanan Khas Daerah",
    icon: "🍜",
    emoji: "🍜",
    description: "Kuliner khas Nusantara",
    color: "orange-400",
    gradient: "from-orange-400 to-red-500",
    href: "/budaya/makanan-khas",
    gameCount: 2,
    bgEmoji: "🍛",
    decoration: "Makanan lezat dari berbagai daerah",
  },
  {
    id: "provinsi",
    name: "Provinsi Indonesia",
    icon: "🏝️",
    emoji: "🏝️",
    description: "38 provinsi di Indonesia",
    color: "cyan-400",
    gradient: "from-cyan-400 to-blue-500",
    href: "/budaya/provinsi",
    gameCount: 2,
    bgEmoji: "🌏",
    decoration: "Peta dan informasi 38 provinsi Indonesia",
  },
  {
    id: "fauna",
    name: "Fauna Indonesia",
    icon: "🦜",
    emoji: "🦜",
    description: "Hewan endemik Indonesia",
    color: "lime-400",
    gradient: "from-lime-400 to-green-500",
    href: "/budaya/fauna",
    gameCount: 2,
    bgEmoji: "🐅",
    decoration: "Hewan-hewan unik dari kepulauan Indonesia",
  },
  {
    id: "flora",
    name: "Flora Indonesia",
    icon: "🌿",
    emoji: "🌿",
    description: "Tumbuhan khas Indonesia",
    color: "emerald-400",
    gradient: "from-emerald-400 to-teal-500",
    href: "/budaya/flora",
    gameCount: 2,
    bgEmoji: "🌺",
    decoration: "Bunga dan tumbuhan dari seluruh Nusantara",
  },
  {
    id: "pahlawan",
    name: "Pahlawan Nasional",
    icon: "🏛️",
    emoji: "🏛️",
    description: "Pahlawan kemerdekaan Indonesia",
    color: "yellow-400",
    gradient: "from-yellow-400 to-amber-500",
    href: "/budaya/pahlawan",
    gameCount: 2,
    bgEmoji: "🎖️",
    decoration: "Pahlawan-pahlawan yang berjuang untuk kemerdekaan",
  },
  {
    id: "keajaiban-alam",
    name: "Keajaiban Alam Indonesia",
    icon: "🗺️",
    emoji: "🗺️",
    description: "Keindahan alam Nusantara",
    color: "sky-400",
    gradient: "from-sky-400 to-cyan-500",
    href: "/budaya/keajaiban-alam",
    gameCount: 2,
    bgEmoji: "🗻",
    decoration: "Keajaiban alam dari Sabang sampai Merauke",
  },
];
